services:
    backend_app:
        build: .
        ports:
        - "5000:5000"
        volumes:
        - backend-app-data:/var/lib/backend-app/data
        depends_on:
        - db
        environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/beam_backend_db
    db:
        image: postgres:latest
        environment:
          POSTGRES_DB: beam_backend_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
        - "5432:5432"

volumes:
    backend-app-data:
    postgres-data:

