POST http://localhost:8080/api/v1/auth/login

{
       "email": "email@gmail.com",
       "password": "password"
}



POST http://localhost:8080/api/v1/auth/register

{
       "email": "email@gmail.com",
       "password": "password",
       "firstName": "firstName",
       "lastName": "lastName"
}